# Bindgen whitelist

types = [
  "btrfs_util_error",
  "btrfs_util_subvolume_info",
  "btrfs_util_qgroup_inherit",
  "btrfs_util_subvolume_iterator",
]

functions = [
  "btrfs_util_strerror",
  "btrfs_util_sync",
  "btrfs_util_sync_fd",
  "btrfs_util_start_sync",
  "btrfs_util_start_sync_fd",
  "btrfs_util_wait_sync",
  "btrfs_util_wait_sync_fd",
  "btrfs_util_is_subvolume",
  "btrfs_util_is_subvolume_fd",
  "btrfs_util_subvolume_id",
  "btrfs_util_subvolume_id_fd",
  "btrfs_util_subvolume_path",
  "btrfs_util_subvolume_path_fd",
  "btrfs_util_subvolume_info",
  "btrfs_util_subvolume_info_fd",
  "btrfs_util_get_subvolume_read_only",
  "btrfs_util_get_subvolume_read_only_fd",
  "btrfs_util_set_subvolume_read_only",
  "btrfs_util_set_subvolume_read_only_fd",
  "btrfs_util_get_default_subvolume",
  "btrfs_util_get_default_subvolume_fd",
  "btrfs_util_set_default_subvolume",
  "btrfs_util_set_default_subvolume_fd",
  "btrfs_util_create_subvolume",
  "btrfs_util_create_subvolume_fd",
  "btrfs_util_create_snapshot",
  "btrfs_util_create_snapshot_fd",
  "btrfs_util_create_snapshot_fd2",
  "btrfs_util_delete_subvolume",
  "btrfs_util_delete_subvolume_fd",
  "btrfs_util_delete_subvolume_by_id_fd",
  "btrfs_util_create_subvolume_iterator",
  "btrfs_util_create_subvolume_iterator_fd",
  "btrfs_util_destroy_subvolume_iterator",
  "btrfs_util_subvolume_iterator_fd",
  "btrfs_util_subvolume_iterator_next",
  "btrfs_util_subvolume_iterator_next_info",
  "btrfs_util_deleted_subvolumes",
  "btrfs_util_deleted_subvolumes_fd",
  "btrfs_util_create_qgroup_inherit",
  "btrfs_util_destroy_qgroup_inherit",
  "btrfs_util_qgroup_inherit_add_group",
  "btrfs_util_qgroup_inherit_get_groups",
]

vars = [
  "BTRFS_UTIL_CREATE_SNAPSHOT_RECURSIVE",
  "BTRFS_UTIL_CREATE_SNAPSHOT_READ_ONLY",
  "BTRFS_UTIL_CREATE_SNAPSHOT_MASK",
  "BTRFS_UTIL_DELETE_SUBVOLUME_RECURSIVE",
  "BTRFS_UTIL_DELETE_SUBVOLUME_MASK",
  "BTRFS_UTIL_SUBVOLUME_ITERATOR_POST_ORDER",
  "BTRFS_UTIL_SUBVOLUME_ITERATOR_MASK",
] 
